development:
  adapter: postgresql
  database: plant-mom_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: plant-mom_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: plant-mom_production
  pool: 5
  timeout: 5000